# Generated by Django 5.0.6 on 2024-05-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_profile_picture_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default_avatar.png', upload_to='profile_pics/%Y/%m/%d/'),
        ),
    ]
