# Generated by Django 5.0.6 on 2024-05-24 20:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default_avatar.png', upload_to=accounts.models.user_profile_picture_upload_path),
        ),
    ]
